# Generated by Django 2.2.6 on 2019-11-14 19:06

import activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('headline', models.CharField(blank=True, max_length=128)),
                ('description_html', activities.models.HtmlBlob(blank=True)),
                ('address_text', activities.models.PlainTextField(blank=True, max_length=2048)),
                ('address_postcode', activities.models.PlainTextField(blank=True, max_length=10)),
                ('address_latitudinal', models.DecimalField(decimal_places=8, default=None, max_digits=12)),
                ('address_longitudinal', models.DecimalField(decimal_places=8, default=None, max_digits=12)),
                ('external_link', models.URLField(blank=True, max_length=1024)),
                ('price_rating', activities.models.PriceRatingField(choices=[(1, 'Free'), (2, 'Low Price'), (3, 'Medium Price'), (4, 'High Price'), (5, 'Premium Price')])),
                ('is_outdoor', activities.models.YesNoField(choices=[(1, 'Yes'), (2, 'No')])),
                ('intimate', activities.models.IntimateField(choices=[(1, 'Casual & Relaxed'), (2, 'Cosy & Intimate'), (3, 'Sexy & Romantic')])),
                ('booking_required', activities.models.BookingRequiredField(choices=[(2, 'No'), (3, 'Recommended'), (1, 'Yes')])),
                ('time_of_day', activities.models.TimeOfDayField(choices=[(3, 'Any time (day or night)'), (1, 'Day time only'), (2, 'Night time only')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('event_type', models.CharField(choices=[('Museum', 'Museum'), ('Music', 'Music'), ('Outdoor', 'Outdoor'), ('Activity', 'Activity'), ('Market', 'Market'), ('Sport', 'Sport'), ('Hobby', 'Hobby'), ('Tour', 'Tour'), ('Comedy', 'Comedy'), ('Theatre', 'Theatre'), ('Other Event', 'Other Event')], default='Other Event', max_length=32)),
                ('is_cardio', activities.models.CardioLevelField(choices=[(1, 'None / Inactive'), (2, 'Low level of cardio'), (3, 'Mild level of cardio'), (4, 'Some cardio / active'), (5, 'High level / Very active cardio')])),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='MealActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('meal_type', models.CharField(choices=[('Bar', 'Bar'), ('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Picnic', 'Picnic'), ('Other Meal', 'Other Meal')], default='Other Meal', max_length=32)),
            ],
            bases=('activities.activity',),
        ),
    ]
